keep:
  - any_duplicated
  - any_is_na
  - class_equals
  - condition_message
  - double_assignment
  - duplicate_argument
  - empty_assignment
  - equal_assignment
  - equals_na
  - expect_comparison
  - expect_length
  - expect_named
  - expect_not
  - expect_null
  - expect_true_false
  - expect_type
  - for_loop_index
  - function_return
  - implicit_assignment
  - is_numeric
  - length_levels
  - length_test
  - lengths
  - library_call
  - list_comparison
  - literal_coercion
  - matrix_apply
  - missing_argument
  - nested_ifelse
  - numeric_leading_zero
  - outer_negation
  - package_hooks
  - paste
  - redundant_equals
  - redundant_ifelse
  - rep_len
  - right_assignment
  - sample_int
  - seq
  - sort
  - stopifnot_all
  - T_and_F_symbol
  - undesirable_operator
  - unnecessary_nesting
  - unreachable_code
  - which_grepl

exclude:
  - expect_identical
  - todo_comment
  - undesirable_function
